name: Cypress Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Run Cypress tests
              run: pnpx cypress run